---
title: "Result_analysis"
author: "Yicheng Shen"
date: "2023-04-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
```


```{r}
load("bias_result.Rdata")
```

```{r}
bias_result %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias"), names_to = "Bias_Type", values_to = "Bias") %>% 
  ggplot(aes(x = gamma, y = Bias, color = Bias_Type)) + geom_point() + facet_wrap(~confound_treatment)


bias_result %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias"), names_to = "Bias_Type", values_to = "Bias") %>% 
  ggplot(aes(x = rho, y = Bias, color = Bias_Type)) + geom_point() + facet_wrap(~confound_treatment)
```


```{r}
bias_result %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type!="OLS_bias") %>% 
  ggplot(aes(x = gamma, y = Bias, color = Bias_Type)) + geom_point() + facet_wrap(~confound_treatment)


bias_result %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type!="OLS_bias") %>% 
  ggplot(aes(x = rho, y = Bias, color = Bias_Type)) + geom_point() + facet_wrap(~confound_treatment)
```


```{r}
load("bias_result_uniform.Rdata")
```

```{r}
bias_result_uniform %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias"), names_to = "Bias_Type", values_to = "Bias") %>% 
  ggplot(aes(x = gamma, y = Bias, color = Bias_Type)) + geom_point() 


bias_result_uniform %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias"), names_to = "Bias_Type", values_to = "Bias") %>% 
  ggplot(aes(x = rho, y = Bias, color = Bias_Type)) + geom_point() 



bias_result_uniform %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type!="OLS_bias") %>% 
  ggplot(aes(x = gamma, y = Bias, color = Bias_Type)) + geom_point() 


bias_result_uniform %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type!="OLS_bias") %>% 
  ggplot(aes(x = rho, y = Bias, color = Bias_Type)) + geom_point() 
```


```{r}
load("bias_result_full.RData")
bias_result_full$confound_treatment = factor(bias_result_full$confound_treatment)
levels(bias_result_full$confound_treatment)[levels(bias_result_full$confound_treatment)=="Uniform"] <- "Very Strong"


bias_result_full %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(rho == 5) %>%
  ggplot(aes(x = gamma, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)


bias_result_full %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(gamma == 5) %>%
  ggplot(aes(x = rho, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)
```


```{r}
bias_result_full %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type != "OLS_bias", rho == 5) %>% 
  ggplot(aes(x = gamma, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)


bias_result_full %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type != "OLS_bias", gamma == 5) %>%
  ggplot(aes(x = rho, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)
```

```{r}
bias_result_full %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type != "OLS_bias") %>% 
  ggplot(aes(x = gamma, y = Bias, color = Bias_Type)) + geom_point() + facet_wrap(~confound_treatment)


bias_result_full %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type != "OLS_bias") %>%
  ggplot(aes(x = rho, y = Bias, color = Bias_Type)) + geom_point() + facet_wrap(~confound_treatment)
```


```{r}
bias_result_full %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type != "OLS_bias") %>%
  ggplot(aes(x = gamma, y = Bias, color = Bias_Type, alpha = rho)) + geom_point() + facet_wrap(~confound_treatment)

bias_result_full %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type != "OLS_bias") %>%
  ggplot(aes(x = rho, y = Bias, color = Bias_Type, alpha = gamma)) + geom_point() + facet_wrap(~confound_treatment)


bias_result_full %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type %in% c("DID_bias","FE_bias")) %>%
  ggplot(aes(x = rho, y = Bias, color = Bias_Type)) + geom_point() + facet_wrap(~confound_treatment)

bias_result_full %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type %in% c("DID_bias","FE_bias"), gamma == 5) %>%
  ggplot(aes(x = rho, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)
```

```{r}
bias_result_full %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type %in% c("FE_bias","RE_bias"), gamma == 3) %>%   ggplot(aes(x = rho, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)

 bias_result_full %>% mutate(differ = RE_est - FE_est) %>% ggplot(aes(x = gamma, y = differ)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)
```


```{r}
correlation = c()
for (i in 1:1000)
{
  correlation[i] = cor(rnorm(100),rnorm(100))
}
mean(abs(correlation))
```


```{r}
load("bias_result_full_by_n.RData")
bias_result_full_by_n$confound_treatment = factor(bias_result_full_by_n$confound_treatment)
levels(bias_result_full_by_n$confound_treatment)[levels(bias_result_full_by_n$confound_treatment)=="Uniform"] <- "Very Strong"

bias_result_full_by_n %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  ggplot(aes(x = n, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)

bias_result_full_by_n %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type %in% c("DID_bias", "FE_bias","RE_bias")) %>%   ggplot(aes(x = n, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)

bias_result_full_by_n %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type %in% c("FE_bias","RE_bias")) %>%   ggplot(aes(x = n, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)

bias_result_full_by_n %>% pivot_longer(cols = c("DID_bias","OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type %in% c("FE_bias","DID_bias")) %>%   ggplot(aes(x = n, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)
```
```{r}
load("bias_result_no_interaction.RData")
bias_result_no_interaction$confound_treatment = factor(bias_result_no_interaction$confound_treatment)
levels(bias_result_no_interaction$confound_treatment)[levels(bias_result_no_interaction$confound_treatment)=="Uniform"] <- "Very Strong"

bias_result_no_interaction %>% pivot_longer(cols = c("OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(rho == 4) %>% 
  ggplot(aes(x = gamma, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)

bias_result_no_interaction %>% pivot_longer(cols = c("OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(gamma == 4) %>% 
  ggplot(aes(x = rho, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)

bias_result_no_interaction %>% pivot_longer(cols = c("OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type != "OLS_bias", rho == 4) %>% 
  ggplot(aes(x = gamma, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)

bias_result_no_interaction %>% pivot_longer(cols = c("OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type != "OLS_bias", gamma == 4) %>%
  ggplot(aes(x = rho, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)
```

```{r}
load("bias_result_interaction.RData")
# load("bias_result_interaction2.RData")
bias_result_interaction$confound_treatment = factor(bias_result_interaction$confound_treatment)
levels(bias_result_interaction$confound_treatment)[levels(bias_result_interaction$confound_treatment)=="Uniform"] <- "Very Strong"

bias_result_interaction %>% pivot_longer(cols = c("OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(rho == 10, phi == 10) %>% 
  ggplot(aes(x = gamma, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)

bias_result_interaction %>% pivot_longer(cols = c("OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(gamma == 10, phi == 10) %>% 
  ggplot(aes(x = rho, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)

bias_result_interaction %>% pivot_longer(cols = c("OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(gamma == 10, rho == 10) %>% 
  ggplot(aes(x = phi, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)

bias_result_interaction %>% pivot_longer(cols = c("OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type != "OLS_bias", rho == 10, phi == 10) %>% 
  ggplot(aes(x = gamma, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)

bias_result_interaction %>% pivot_longer(cols = c("OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type != "OLS_bias", gamma == 10, phi == 10) %>%
  ggplot(aes(x = rho, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)

bias_result_interaction %>% pivot_longer(cols = c("OLS_bias","FE_bias", "RE_bias"), names_to = "Bias_Type", values_to = "Bias") %>%
  filter(Bias_Type != "OLS_bias", rho == 10, gamma == 10) %>% 
  ggplot(aes(x = phi, y = Bias, color = Bias_Type)) + geom_point() + geom_line() + facet_wrap(~confound_treatment)

```



